/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CycleMessage.as).
 */

package com.photodispatcher.model.mysql.entities.messenger {

    import com.photodispatcher.model.mysql.entities.AbstractEntity;
    import com.photodispatcher.model.mysql.entities.PrintGroup;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class CycleMessageBase extends AbstractEntity {

        public function CycleMessageBase() {
            super();
        }

        private var _command:int;
        private var _message:String;
        private var _pgroup_info:PrintGroup;
        private var _recipient:String;
        private var _sender:CycleStation;
        private var _topic:String;

        public function set command(value:int):void {
            _command = value;
        }
        public function get command():int {
            return _command;
        }

        public function set message(value:String):void {
            _message = value;
        }
        public function get message():String {
            return _message;
        }

        public function set pgroup_info(value:PrintGroup):void {
            _pgroup_info = value;
        }
        public function get pgroup_info():PrintGroup {
            return _pgroup_info;
        }

        public function set recipient(value:String):void {
            _recipient = value;
        }
        public function get recipient():String {
            return _recipient;
        }

        public function set sender(value:CycleStation):void {
            _sender = value;
        }
        public function get sender():CycleStation {
            return _sender;
        }

        public function set topic(value:String):void {
            _topic = value;
        }
        public function get topic():String {
            return _topic;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _command = input.readObject() as int;
            _message = input.readObject() as String;
            _pgroup_info = input.readObject() as PrintGroup;
            _recipient = input.readObject() as String;
            _sender = input.readObject() as CycleStation;
            _topic = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_command is IPropertyHolder) ? IPropertyHolder(_command).object : _command);
            output.writeObject((_message is IPropertyHolder) ? IPropertyHolder(_message).object : _message);
            output.writeObject((_pgroup_info is IPropertyHolder) ? IPropertyHolder(_pgroup_info).object : _pgroup_info);
            output.writeObject((_recipient is IPropertyHolder) ? IPropertyHolder(_recipient).object : _recipient);
            output.writeObject((_sender is IPropertyHolder) ? IPropertyHolder(_sender).object : _sender);
            output.writeObject((_topic is IPropertyHolder) ? IPropertyHolder(_topic).object : _topic);
        }
    }
}