/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.services {

    [RemoteClass(alias="com.photodispatcher.model.mysql.services.BookSynonymService")]
    public class BookSynonymService extends BookSynonymServiceBase {
    }
    
}
