/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AttrType.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class AttrTypeBase extends AbstractEntity {

        public function AttrTypeBase() {
            super();
        }

        private var _attr_fml:int;
        private var _field:String;
        private var _id:int;
        private var _list:Boolean;
        private var _name:String;
        private var _persist:Boolean;

        public function set attr_fml(value:int):void {
            _attr_fml = value;
        }
        public function get attr_fml():int {
            return _attr_fml;
        }

        public function set field(value:String):void {
            _field = value;
        }
        public function get field():String {
            return _field;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set list(value:Boolean):void {
            _list = value;
        }
        public function get list():Boolean {
            return _list;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set persist(value:Boolean):void {
            _persist = value;
        }
        public function get persist():Boolean {
            return _persist;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _attr_fml = input.readObject() as int;
            _field = input.readObject() as String;
            _id = input.readObject() as int;
            _list = input.readObject() as Boolean;
            _name = input.readObject() as String;
            _persist = input.readObject() as Boolean;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_attr_fml);
            output.writeObject(_field);
            output.writeObject(_id);
            output.writeObject(_list);
            output.writeObject(_name);
            output.writeObject(_persist);
        }
    }
}