/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.DeliveryType")]
    public class DeliveryType extends DeliveryTypeBase {
		public static const TYPE_AT:int=5;

        public function DeliveryType() {
            super();
        }
    }
}