/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (FieldValue.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class FieldValueBase extends AbstractEntity {

        private var _field:String;
        private var _label:String;
        private var _src_type:int;
        private var _synonym:String;
        private var _value:int;

        public function set field(value:String):void {
            _field = value;
        }
        public function get field():String {
            return _field;
        }

        public function set label(value:String):void {
            _label = value;
        }
        public function get label():String {
            return _label;
        }

        public function set src_type(value:int):void {
            _src_type = value;
        }
        public function get src_type():int {
            return _src_type;
        }

        public function set synonym(value:String):void {
            _synonym = value;
        }
        public function get synonym():String {
            return _synonym;
        }

        public function set value(value:int):void {
            _value = value;
        }
        public function get value():int {
            return _value;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _field = input.readObject() as String;
            _label = input.readObject() as String;
            _src_type = input.readObject() as int;
            _synonym = input.readObject() as String;
            _value = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_field is IPropertyHolder) ? IPropertyHolder(_field).object : _field);
            output.writeObject((_label is IPropertyHolder) ? IPropertyHolder(_label).object : _label);
            output.writeObject((_src_type is IPropertyHolder) ? IPropertyHolder(_src_type).object : _src_type);
            output.writeObject((_synonym is IPropertyHolder) ? IPropertyHolder(_synonym).object : _synonym);
            output.writeObject((_value is IPropertyHolder) ? IPropertyHolder(_value).object : _value);
        }
    }
}