/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	import mx.collections.ArrayList;
	
	import spark.components.gridClasses.GridColumn;

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.Lab")]
    public class Lab extends LabBase {
		
		public static function gridColumns():ArrayList{
			var result:ArrayList= new ArrayList();
			var col:GridColumn= new GridColumn('id'); col.headerText='ID'; result.addItem(col);
			col= new GridColumn('src_type_name'); col.headerText='Тип'; result.addItem(col); 
			col= new GridColumn('name'); col.headerText='Наименование'; result.addItem(col); 
			col= new GridColumn('hot'); col.headerText='Hot folder'; result.addItem(col); 
			col= new GridColumn('hot_nfs'); col.headerText='Hot folder NHF'; result.addItem(col); 
			col= new GridColumn('is_managed'); col.headerText='Автораспределение'; result.addItem(col); 
			col= new GridColumn('queue_limit'); col.headerText='Очередь печати (мин)'; result.addItem(col); 
			col= new GridColumn('is_managed'); col.headerText='Автопечать'; result.addItem(col); 
			col= new GridColumn('is_active'); col.headerText='Активна'; result.addItem(col); 
			return result;
		}

		//runtime, 4 Laboratory config
		public var isSelected:Boolean;

		public function cloneTo(lab:Lab):void{
			if(!lab) return;
			lab.id=this.id;
			lab.src_type=this.src_type;
			lab.name=this.name;
			lab.hot=this.hot;
			lab.hot_nfs=this.hot_nfs;
			lab.queue_limit=this.queue_limit;
			lab.is_active=this.is_active;
			lab.is_managed=this.is_managed;
			lab.src_type_name=this.src_type_name;
			lab.devices=this.devices;
			lab.profiles=this.profiles;
			lab.isSelected=this.isSelected;
			lab.post_delay=this.post_delay;
			lab.pusher_enabled=this.pusher_enabled;
				
		}

    }
}