/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Lab.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class LabBase extends AbstractEntity {

        public function LabBase() {
            super();
        }

        private var _devices:ListCollectionView;
        private var _hot:String;
        private var _hot_nfs:String;
        private var _id:int;
        private var _isSelected:Boolean;
        private var _is_active:Boolean;
        private var _is_managed:Boolean;
        private var _name:String;
        private var _post_delay:Number;
        private var _profiles:ListCollectionView;
        private var _pusher_enabled:Boolean;
        private var _queue_limit:int;
        private var _soft_speed:Number;
        private var _src_type:int;
        private var _src_type_name:String;
        private var _url:String;

        public function set devices(value:ListCollectionView):void {
            _devices = value;
        }
        public function get devices():ListCollectionView {
            return _devices;
        }

        public function set hot(value:String):void {
            _hot = value;
        }
        public function get hot():String {
            return _hot;
        }

        public function set hot_nfs(value:String):void {
            _hot_nfs = value;
        }
        public function get hot_nfs():String {
            return _hot_nfs;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set is_active(value:Boolean):void {
            _is_active = value;
        }
        public function get is_active():Boolean {
            return _is_active;
        }

        public function set is_managed(value:Boolean):void {
            _is_managed = value;
        }
        public function get is_managed():Boolean {
            return _is_managed;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set post_delay(value:Number):void {
            _post_delay = value;
        }
        public function get post_delay():Number {
            return _post_delay;
        }

        public function set profiles(value:ListCollectionView):void {
            _profiles = value;
        }
        public function get profiles():ListCollectionView {
            return _profiles;
        }

        public function set pusher_enabled(value:Boolean):void {
            _pusher_enabled = value;
        }
        public function get pusher_enabled():Boolean {
            return _pusher_enabled;
        }

        public function set queue_limit(value:int):void {
            _queue_limit = value;
        }
        public function get queue_limit():int {
            return _queue_limit;
        }

        public function set soft_speed(value:Number):void {
            _soft_speed = value;
        }
        public function get soft_speed():Number {
            return _soft_speed;
        }

        public function set src_type(value:int):void {
            _src_type = value;
        }
        public function get src_type():int {
            return _src_type;
        }

        public function set src_type_name(value:String):void {
            _src_type_name = value;
        }
        public function get src_type_name():String {
            return _src_type_name;
        }

        public function set url(value:String):void {
            _url = value;
        }
        public function get url():String {
            return _url;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _devices = input.readObject() as ListCollectionView;
            _hot = input.readObject() as String;
            _hot_nfs = input.readObject() as String;
            _id = input.readObject() as int;
            _isSelected = input.readObject() as Boolean;
            _is_active = input.readObject() as Boolean;
            _is_managed = input.readObject() as Boolean;
            _name = input.readObject() as String;
            _post_delay = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _profiles = input.readObject() as ListCollectionView;
            _pusher_enabled = input.readObject() as Boolean;
            _queue_limit = input.readObject() as int;
            _soft_speed = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _src_type = input.readObject() as int;
            _src_type_name = input.readObject() as String;
            _url = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_devices);
            output.writeObject(_hot);
            output.writeObject(_hot_nfs);
            output.writeObject(_id);
            output.writeObject(_isSelected);
            output.writeObject(_is_active);
            output.writeObject(_is_managed);
            output.writeObject(_name);
            output.writeObject(_post_delay);
            output.writeObject(_profiles);
            output.writeObject(_pusher_enabled);
            output.writeObject(_queue_limit);
            output.writeObject(_soft_speed);
            output.writeObject(_src_type);
            output.writeObject(_src_type_name);
            output.writeObject(_url);
        }
    }
}