/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	import com.photodispatcher.view.itemRenderer.BooleanGridRenderer;
	
	import mx.collections.ArrayList;
	import mx.core.ClassFactory;
	
	import spark.components.gridClasses.GridColumn;

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.LabRoll")]
    public class LabRoll extends LabRollBase {
		//run time
		public var printQueueLen:int=0;
		public var printQueueTime:int=0;//sec
		public var speed:int=0;//mm/sec
		public var printGroups:Array=[];
		
		public static function gridColumnsEdit():ArrayList{
			var result:ArrayList= new ArrayList();
			var col:GridColumn;
			col= new GridColumn('is_used'); col.headerText=' '; col.itemRenderer=new ClassFactory(BooleanGridRenderer); col.editable=false; col.width=30; result.addItem(col);
			col= new GridColumn('width'); col.headerText='Ширина'; col.editable=false; result.addItem(col);
			col= new GridColumn('paper_name'); col.headerText='Бумага'; col.editable=false; result.addItem(col);
			col= new GridColumn('len_std'); col.headerText='Стандартная длинна (мм)'; result.addItem(col);
			return result;
		}
		
		public static function gridColumnsView(brief:Boolean=false):ArrayList{
			var result:ArrayList= new ArrayList();
			var col:GridColumn;
			if(!brief){ col= new GridColumn('is_online'); col.headerText='Активный'; col.itemRenderer=new ClassFactory(BooleanGridRenderer); col.editable=false; col.width=70; result.addItem(col);}
			col= new GridColumn('width'); col.headerText='Ширина'; col.editable=false; result.addItem(col);
			col= new GridColumn('paper_name'); col.headerText='Бумага'; col.editable=false; result.addItem(col);
			col= new GridColumn('len'); col.headerText='Длинна (мм)'; result.addItem(col);
			return result;
		}
		
		public function clone():LabRoll{
			var result:LabRoll= new LabRoll();
			result.lab_device=lab_device;
			result.paper=paper;
			result.width=width;
			result.speed=speed;
			result.paper_name=paper_name;
			result.len_std=len_std;
			result.len=len;
			result.is_online=is_online;
			return result;
		}

    }
}