/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	
	[Bindable]
	[RemoteClass(alias="com.photodispatcher.model.mysql.entities.LabStopType")]
	public class LabStopType extends LabStopTypeBase {
		
		/**
		 * 0, Другое
		 */
		public static const OTHER:int = 0;
		
		/**
		 * 1, Нет заказов
		 */
		public static const NO_ORDER:int = 1;
		
		/**
		 * 2, Замена рулона
		 */
		public static const ROLL_CHANGE:int = 2;
		
		public function LabStopType() {
			super();
		}
	}
}