/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	import com.photodispatcher.model.mysql.DbLatch;
	import com.photodispatcher.model.mysql.services.LabService;
	
	import flash.events.Event;
	
	import org.granite.tide.Tide;
	
	[Bindable]
	[RemoteClass(alias="com.photodispatcher.model.mysql.entities.LabStopType")]
	public class LabStopType extends LabStopTypeBase {
		
		/**
		 * 0, Другое
		 */
		public static const OTHER:int = 0;
		
		/**
		 * 1, Нет заказов
		 */
		public static const NO_ORDER:int = 1;
		
		/**
		 * 2, Замена рулона
		 */
		public static const ROLL_CHANGE:int = 2;
		/**
		 * 3, Постановка на печать
		 */
		public static const POST_WAITE:int = 3;
		public static const NO_COMPATIBLE_ORDER:int = 4;
		public static const WRONG_ONLINE_ROLL:int = 5;
		
		
		private static var itemsMap:Object;
		
		public static function initMap():DbLatch{
			var svc:LabService=Tide.getInstance().getContext().byType(LabService,true) as LabService;
			var latch:DbLatch= new DbLatch();
			latch.debugName='LabStopType.initStateMap';
			latch.addEventListener(Event.COMPLETE, onLoad);
			latch.addLatch(svc.loadLabStopType());
			latch.start();
			return latch;
			/*
			itemsMap=new Object;
			itemsMap[OTHER]='Другое';
			itemsMap[NO_ORDER]='Нет заказов';
			itemsMap[ROLL_CHANGE]='Замена рулона';
			itemsMap[POST_WAITE]='Постановка на печать';
			itemsMap[NO_COMPATIBLE_ORDER]='Нет подходящего заказа';
			return null;
			*/
		}

		private static function onLoad(event:Event):void{
			var latch:DbLatch= event.target as DbLatch;
			if(latch){
				latch.removeEventListener(Event.COMPLETE,onLoad);
				if(latch.complite){
					var a:Array=latch.lastDataArr;
					if(!a) return;
					itemsMap=new Object();
					for each(var o:LabStopType in a){
						if(o) itemsMap[o.id]=o.name;
					}
				}
			}
		}

		public static function getStopTypeName(stopType:int):String{
			var res:String;
			if(itemsMap) res=itemsMap[stopType];
			if(!res) res='Тип id: '+ stopType.toString();
			return res;
		}
		
		public function LabStopType() {
			super();
		}
	}
}