/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (LabTimetable.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class LabTimetableBase extends AbstractEntity {

        private var _day_id:int;
        private var _day_id_name:String;
        private var _is_online:Boolean;
        private var _lab_device:int;
        private var _time_from:Date;
        private var _time_to:Date;

        public function set day_id(value:int):void {
            _day_id = value;
        }
        public function get day_id():int {
            return _day_id;
        }

        public function set day_id_name(value:String):void {
            _day_id_name = value;
        }
        public function get day_id_name():String {
            return _day_id_name;
        }

        public function set is_online(value:Boolean):void {
            _is_online = value;
        }
        public function get is_online():Boolean {
            return _is_online;
        }

        public function set lab_device(value:int):void {
            _lab_device = value;
        }
        public function get lab_device():int {
            return _lab_device;
        }

        public function set time_from(value:Date):void {
            _time_from = value;
        }
        public function get time_from():Date {
            return _time_from;
        }

        public function set time_to(value:Date):void {
            _time_to = value;
        }
        public function get time_to():Date {
            return _time_to;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _day_id = input.readObject() as int;
            _day_id_name = input.readObject() as String;
            _is_online = input.readObject() as Boolean;
            _lab_device = input.readObject() as int;
            _time_from = input.readObject() as Date;
            _time_to = input.readObject() as Date;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_day_id is IPropertyHolder) ? IPropertyHolder(_day_id).object : _day_id);
            output.writeObject((_day_id_name is IPropertyHolder) ? IPropertyHolder(_day_id_name).object : _day_id_name);
            output.writeObject((_is_online is IPropertyHolder) ? IPropertyHolder(_is_online).object : _is_online);
            output.writeObject((_lab_device is IPropertyHolder) ? IPropertyHolder(_lab_device).object : _lab_device);
            output.writeObject((_time_from is IPropertyHolder) ? IPropertyHolder(_time_from).object : _time_from);
            output.writeObject((_time_to is IPropertyHolder) ? IPropertyHolder(_time_to).object : _time_to);
        }
    }
}