/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MailPackageBoxItem.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class MailPackageBoxItemBase extends AbstractEntity {

        public function MailPackageBoxItemBase() {
            super();
        }

        private var _alias:String;
        private var _bookType:int;
        private var _bookTypeName:String;
        private var _boxID:String;
        private var _itemFrom:int;
        private var _itemTo:int;
        private var _orderID:String;
        private var _printGroups:ListCollectionView;
        private var _state:int;
        private var _state_date:Date;
        private var _state_name:String;

        public function set alias(value:String):void {
            _alias = value;
        }
        public function get alias():String {
            return _alias;
        }

        public function set bookType(value:int):void {
            _bookType = value;
        }
        public function get bookType():int {
            return _bookType;
        }

        public function set bookTypeName(value:String):void {
            _bookTypeName = value;
        }
        public function get bookTypeName():String {
            return _bookTypeName;
        }

        public function set boxID(value:String):void {
            _boxID = value;
        }
        public function get boxID():String {
            return _boxID;
        }

        public function set itemFrom(value:int):void {
            _itemFrom = value;
        }
        public function get itemFrom():int {
            return _itemFrom;
        }

        public function set itemTo(value:int):void {
            _itemTo = value;
        }
        public function get itemTo():int {
            return _itemTo;
        }

        public function set orderID(value:String):void {
            _orderID = value;
        }
        public function get orderID():String {
            return _orderID;
        }

        public function set printGroups(value:ListCollectionView):void {
            _printGroups = value;
        }
        public function get printGroups():ListCollectionView {
            return _printGroups;
        }

        public function set state(value:int):void {
            _state = value;
        }
        public function get state():int {
            return _state;
        }

        public function set state_date(value:Date):void {
            _state_date = value;
        }
        public function get state_date():Date {
            return _state_date;
        }

        public function set state_name(value:String):void {
            _state_name = value;
        }
        public function get state_name():String {
            return _state_name;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _alias = input.readObject() as String;
            _bookType = input.readObject() as int;
            _bookTypeName = input.readObject() as String;
            _boxID = input.readObject() as String;
            _itemFrom = input.readObject() as int;
            _itemTo = input.readObject() as int;
            _orderID = input.readObject() as String;
            _printGroups = input.readObject() as ListCollectionView;
            _state = input.readObject() as int;
            _state_date = input.readObject() as Date;
            _state_name = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_alias);
            output.writeObject(_bookType);
            output.writeObject(_bookTypeName);
            output.writeObject(_boxID);
            output.writeObject(_itemFrom);
            output.writeObject(_itemTo);
            output.writeObject(_orderID);
            output.writeObject(_printGroups);
            output.writeObject(_state);
            output.writeObject(_state_date);
            output.writeObject(_state_name);
        }
    }
}