/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (OrderExtraMessage.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class OrderExtraMessageBase extends AbstractEntity {

        public function OrderExtraMessageBase() {
            super();
        }

        private var _id:String;
        private var _lod_key:String;
        private var _log_user:String;
        private var _message:String;
        private var _msg_type:int;
        private var _sub_id:String;

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set lod_key(value:String):void {
            _lod_key = value;
        }
        public function get lod_key():String {
            return _lod_key;
        }

        public function set log_user(value:String):void {
            _log_user = value;
        }
        public function get log_user():String {
            return _log_user;
        }

        public function set message(value:String):void {
            _message = value;
        }
        public function get message():String {
            return _message;
        }

        public function set msg_type(value:int):void {
            _msg_type = value;
        }
        public function get msg_type():int {
            return _msg_type;
        }

        public function set sub_id(value:String):void {
            _sub_id = value;
        }
        public function get sub_id():String {
            return _sub_id;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _id = input.readObject() as String;
            _lod_key = input.readObject() as String;
            _log_user = input.readObject() as String;
            _message = input.readObject() as String;
            _msg_type = input.readObject() as int;
            _sub_id = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_id);
            output.writeObject(_lod_key);
            output.writeObject(_log_user);
            output.writeObject(_message);
            output.writeObject(_msg_type);
            output.writeObject(_sub_id);
        }
    }
}