/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.OrderFile")]
    public class OrderFile extends OrderFileBase {

        public function OrderFile() {
            super();
			state=OrderState.FTP_WAITE;
        }

		override public function set state(value:int):void{
			if(super.state != value) state_name= OrderState.getStateName(value);
			super.state = value;
			state_date= new Date();
		}
		override public function get state():int{
			return super.state;
		}

    }
}