/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (OrderTemp.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class OrderTempBase extends AbstractEntity {

        public function OrderTempBase() {
            super();
        }

        private var _clientId:int;
        private var _data_ts:String;
        private var _fotos_num:int;
        private var _ftp_folder:String;
        private var _groupId:int;
        private var _id:String;
        private var _is_preload:Boolean;
        private var _local_folder:String;
        private var _source:int;
        private var _src_date:Date;
        private var _src_id:String;
        private var _state:int;
        private var _state_date:Date;
        private var _sync:int;

        public function set clientId(value:int):void {
            _clientId = value;
        }
        public function get clientId():int {
            return _clientId;
        }

        public function set data_ts(value:String):void {
            _data_ts = value;
        }
        public function get data_ts():String {
            return _data_ts;
        }

        public function set fotos_num(value:int):void {
            _fotos_num = value;
        }
        public function get fotos_num():int {
            return _fotos_num;
        }

        public function set ftp_folder(value:String):void {
            _ftp_folder = value;
        }
        public function get ftp_folder():String {
            return _ftp_folder;
        }

        public function set groupId(value:int):void {
            _groupId = value;
        }
        public function get groupId():int {
            return _groupId;
        }

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set is_preload(value:Boolean):void {
            _is_preload = value;
        }
        public function get is_preload():Boolean {
            return _is_preload;
        }

        public function set local_folder(value:String):void {
            _local_folder = value;
        }
        public function get local_folder():String {
            return _local_folder;
        }

        public function set source(value:int):void {
            _source = value;
        }
        public function get source():int {
            return _source;
        }

        public function set src_date(value:Date):void {
            _src_date = value;
        }
        public function get src_date():Date {
            return _src_date;
        }

        public function set src_id(value:String):void {
            _src_id = value;
        }
        public function get src_id():String {
            return _src_id;
        }

        public function set state(value:int):void {
            _state = value;
        }
        public function get state():int {
            return _state;
        }

        public function set state_date(value:Date):void {
            _state_date = value;
        }
        public function get state_date():Date {
            return _state_date;
        }

        public function set sync(value:int):void {
            _sync = value;
        }
        public function get sync():int {
            return _sync;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _clientId = input.readObject() as int;
            _data_ts = input.readObject() as String;
            _fotos_num = input.readObject() as int;
            _ftp_folder = input.readObject() as String;
            _groupId = input.readObject() as int;
            _id = input.readObject() as String;
            _is_preload = input.readObject() as Boolean;
            _local_folder = input.readObject() as String;
            _source = input.readObject() as int;
            _src_date = input.readObject() as Date;
            _src_id = input.readObject() as String;
            _state = input.readObject() as int;
            _state_date = input.readObject() as Date;
            _sync = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_clientId is IPropertyHolder) ? IPropertyHolder(_clientId).object : _clientId);
            output.writeObject((_data_ts is IPropertyHolder) ? IPropertyHolder(_data_ts).object : _data_ts);
            output.writeObject((_fotos_num is IPropertyHolder) ? IPropertyHolder(_fotos_num).object : _fotos_num);
            output.writeObject((_ftp_folder is IPropertyHolder) ? IPropertyHolder(_ftp_folder).object : _ftp_folder);
            output.writeObject((_groupId is IPropertyHolder) ? IPropertyHolder(_groupId).object : _groupId);
            output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id);
            output.writeObject((_is_preload is IPropertyHolder) ? IPropertyHolder(_is_preload).object : _is_preload);
            output.writeObject((_local_folder is IPropertyHolder) ? IPropertyHolder(_local_folder).object : _local_folder);
            output.writeObject((_source is IPropertyHolder) ? IPropertyHolder(_source).object : _source);
            output.writeObject((_src_date is IPropertyHolder) ? IPropertyHolder(_src_date).object : _src_date);
            output.writeObject((_src_id is IPropertyHolder) ? IPropertyHolder(_src_id).object : _src_id);
            output.writeObject((_state is IPropertyHolder) ? IPropertyHolder(_state).object : _state);
            output.writeObject((_state_date is IPropertyHolder) ? IPropertyHolder(_state_date).object : _state_date);
            output.writeObject((_sync is IPropertyHolder) ? IPropertyHolder(_sync).object : _sync);
        }
    }
}