/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (OrderLoad.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class OrderLoadBase extends AbstractEntity {

        public function OrderLoadBase() {
            super();
        }

        private var _clean_fs:Boolean;
        private var _files:ListCollectionView;
        private var _fotos_num:int;
        private var _ftp_folder:String;
        private var _id:String;
        private var _resume_load:Boolean;
        private var _source:int;
        private var _source_code:String;
        private var _source_name:String;
        private var _src_id:String;
        private var _state:int;
        private var _stateLog:ListCollectionView;
        private var _state_date:Date;
        private var _state_name:String;
        private var _sync:int;
        private var _tag:String;

        public function set clean_fs(value:Boolean):void {
            _clean_fs = value;
        }
        public function get clean_fs():Boolean {
            return _clean_fs;
        }

        public function set files(value:ListCollectionView):void {
            _files = value;
        }
        public function get files():ListCollectionView {
            return _files;
        }

        public function set fotos_num(value:int):void {
            _fotos_num = value;
        }
        public function get fotos_num():int {
            return _fotos_num;
        }

        public function set ftp_folder(value:String):void {
            _ftp_folder = value;
        }
        public function get ftp_folder():String {
            return _ftp_folder;
        }

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set resume_load(value:Boolean):void {
            _resume_load = value;
        }
        public function get resume_load():Boolean {
            return _resume_load;
        }

        public function set source(value:int):void {
            _source = value;
        }
        public function get source():int {
            return _source;
        }

        public function set source_code(value:String):void {
            _source_code = value;
        }
        public function get source_code():String {
            return _source_code;
        }

        public function set source_name(value:String):void {
            _source_name = value;
        }
        public function get source_name():String {
            return _source_name;
        }

        public function set src_id(value:String):void {
            _src_id = value;
        }
        public function get src_id():String {
            return _src_id;
        }

        public function set state(value:int):void {
            _state = value;
        }
        public function get state():int {
            return _state;
        }

        public function set stateLog(value:ListCollectionView):void {
            _stateLog = value;
        }
        public function get stateLog():ListCollectionView {
            return _stateLog;
        }

        public function set state_date(value:Date):void {
            _state_date = value;
        }
        public function get state_date():Date {
            return _state_date;
        }

        public function set state_name(value:String):void {
            _state_name = value;
        }
        public function get state_name():String {
            return _state_name;
        }

        public function set sync(value:int):void {
            _sync = value;
        }
        public function get sync():int {
            return _sync;
        }

        public function set tag(value:String):void {
            _tag = value;
        }
        public function get tag():String {
            return _tag;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _clean_fs = input.readObject() as Boolean;
            _files = input.readObject() as ListCollectionView;
            _fotos_num = input.readObject() as int;
            _ftp_folder = input.readObject() as String;
            _id = input.readObject() as String;
            _resume_load = input.readObject() as Boolean;
            _source = input.readObject() as int;
            _source_code = input.readObject() as String;
            _source_name = input.readObject() as String;
            _src_id = input.readObject() as String;
            _state = input.readObject() as int;
            _stateLog = input.readObject() as ListCollectionView;
            _state_date = input.readObject() as Date;
            _state_name = input.readObject() as String;
            _sync = input.readObject() as int;
            _tag = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_clean_fs);
            output.writeObject(_files);
            output.writeObject(_fotos_num);
            output.writeObject(_ftp_folder);
            output.writeObject(_id);
            output.writeObject(_resume_load);
            output.writeObject(_source);
            output.writeObject(_source_code);
            output.writeObject(_source_name);
            output.writeObject(_src_id);
            output.writeObject(_state);
            output.writeObject(_stateLog);
            output.writeObject(_state_date);
            output.writeObject(_state_name);
            output.writeObject(_sync);
            output.writeObject(_tag);
        }
    }
}