/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.OrderExtraState")]
    public class OrderExtraState extends OrderExtraStateBase {
    }
}