/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	import com.photodispatcher.util.GridUtil;
	
	import flash.globalization.DateTimeStyle;
	
	import mx.collections.ArrayCollection;
	import mx.collections.ArrayList;
	
	import spark.components.gridClasses.GridColumn;
	import spark.formatters.DateTimeFormatter;

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.OrderBook")]
    public class OrderBook extends OrderBookBase {

		public static function gridColumns():ArrayList{
			var result:ArrayList= new ArrayList();
			var col:GridColumn;
			col= new GridColumn('book'); col.headerText='№'; col.width=40; result.addItem(col);
			col= new GridColumn('is_rejected'); col.headerText='Брак'; col.labelFunction=GridUtil.booleanToLabel;  col.width=50; result.addItem(col);
			col= new GridColumn('state_name'); col.headerText='Статус'; col.width=110; result.addItem(col); 
			var fmt:DateTimeFormatter=new DateTimeFormatter(); fmt.dateStyle=fmt.timeStyle=DateTimeStyle.SHORT; 
			col= new GridColumn('state_date'); col.headerText='Дата статуса'; col.width=110; col.formatter=fmt;  result.addItem(col);
			return result;
		}

		public static function gridRejectColumns():ArrayList{
			var result:ArrayList= new ArrayList();
			var col:GridColumn;
			col= new GridColumn('book'); col.headerText='№'; col.width=40; result.addItem(col);
			col= new GridColumn('book_part_name'); col.headerText='Часть книги'; col.width=70; result.addItem(col);
			col= new GridColumn('state_name'); col.headerText='Статус'; col.width=110; result.addItem(col); 
			var fmt:DateTimeFormatter=new DateTimeFormatter(); fmt.dateStyle=fmt.timeStyle=DateTimeStyle.SHORT; 
			col= new GridColumn('state_date'); col.headerText='Дата статуса'; col.width=110; col.formatter=fmt;  result.addItem(col);
			col= new GridColumn('sheets'); col.headerText='Разворотов'; result.addItem(col);
			col= new GridColumn('staff_name'); col.headerText='Сотрудник'; result.addItem(col);
			col= new GridColumn('sa_type_name'); col.headerText='Причина'; result.addItem(col);
			col= new GridColumn('sa_remark'); col.headerText='Примечание'; result.addItem(col);

			return result;
		}
		
		
		public function OrderBook(){
			sub_id='';
		}
		
		public override function set state(value:int):void{
			if(super.state != value){
				state_name= OrderState.getStateName(value);
				state_date= new Date();
			}
			super.state = value;
		}
		
		public var hasRejects:Boolean;
		
		public var rejects:ArrayCollection;
		public function addReject(rjBook:OrderBook):void{
			if(!rejects) rejects= new ArrayCollection();
			if(rjBook && rjBook.is_reject && rjBook.target_pg==target_pg && rjBook.book==book){
				hasRejects=true;
				rejects.addItem(rjBook);
			}
		}
		
    }
}