/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrintFormFieldItem.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PrintFormFieldItemBase extends AbstractEntity {

        public function PrintFormFieldItemBase() {
            super();
        }

        private var _attr_type:int;
        private var _child_field:int;
        private var _delemiter:String;
        private var _form_field:int;
        private var _id:int;
        private var _is_field:Boolean;
        private var _prefix:String;
        private var _property:String;
        private var _sequence:int;
        private var _sufix:String;

        public function set attr_type(value:int):void {
            _attr_type = value;
        }
        public function get attr_type():int {
            return _attr_type;
        }

        public function set child_field(value:int):void {
            _child_field = value;
        }
        public function get child_field():int {
            return _child_field;
        }

        public function set delemiter(value:String):void {
            _delemiter = value;
        }
        public function get delemiter():String {
            return _delemiter;
        }

        public function set form_field(value:int):void {
            _form_field = value;
        }
        public function get form_field():int {
            return _form_field;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set is_field(value:Boolean):void {
            _is_field = value;
        }
        public function get is_field():Boolean {
            return _is_field;
        }

        public function set prefix(value:String):void {
            _prefix = value;
        }
        public function get prefix():String {
            return _prefix;
        }

        public function set property(value:String):void {
            _property = value;
        }
        public function get property():String {
            return _property;
        }

        public function set sequence(value:int):void {
            _sequence = value;
        }
        public function get sequence():int {
            return _sequence;
        }

        public function set sufix(value:String):void {
            _sufix = value;
        }
        public function get sufix():String {
            return _sufix;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _attr_type = input.readObject() as int;
            _child_field = input.readObject() as int;
            _delemiter = input.readObject() as String;
            _form_field = input.readObject() as int;
            _id = input.readObject() as int;
            _is_field = input.readObject() as Boolean;
            _prefix = input.readObject() as String;
            _property = input.readObject() as String;
            _sequence = input.readObject() as int;
            _sufix = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_attr_type);
            output.writeObject(_child_field);
            output.writeObject(_delemiter);
            output.writeObject(_form_field);
            output.writeObject(_id);
            output.writeObject(_is_field);
            output.writeObject(_prefix);
            output.writeObject(_property);
            output.writeObject(_sequence);
            output.writeObject(_sufix);
        }
    }
}