/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.PrintFormField")]
    public class PrintFormField extends PrintFormFieldBase {

        public function PrintFormField() {
            super();
        }
    }
}