/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrintGroup.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class PrintGroupBase extends AbstractEntity {

        public function PrintGroupBase() {
            super();
        }

        private var _alias:String;
        private var _book_num:int;
        private var _book_part:int;
        private var _book_part_name:String;
        private var _book_type:int;
        private var _book_type_name:String;
        private var _butt:int;
        private var _correction:int;
        private var _correction_name:String;
        private var _cutting:int;
        private var _cutting_name:String;
        private var _destination:int;
        private var _file_num:int;
        private var _files:ListCollectionView;
        private var _frame:int;
        private var _frame_name:String;
        private var _height:int;
        private var _id:String;
        private var _is_duplex:Boolean;
        private var _is_finalizeprint:Boolean;
        private var _is_pdf:Boolean;
        private var _is_reprint:Boolean;
        private var _is_revers:Boolean;
        private var _lab_name:String;
        private var _order_folder:String;
        private var _order_id:String;
        private var _paper:int;
        private var _paper_name:String;
        private var _path:String;
        private var _prints:int;
        private var _prints_done:int;
        private var _prn_queue:int;
        private var _reprint_id:String;
        private var _sheet_num:int;
        private var _sheets_per_file:int;
        private var _source_id:int;
        private var _source_name:String;
        private var _state:int;
        private var _state_date:Date;
        private var _state_name:String;
        private var _sub_id:String;
        private var _width:int;

        public function set alias(value:String):void {
            _alias = value;
        }
        public function get alias():String {
            return _alias;
        }

        public function set book_num(value:int):void {
            _book_num = value;
        }
        public function get book_num():int {
            return _book_num;
        }

        public function set book_part(value:int):void {
            _book_part = value;
        }
        public function get book_part():int {
            return _book_part;
        }

        public function set book_part_name(value:String):void {
            _book_part_name = value;
        }
        public function get book_part_name():String {
            return _book_part_name;
        }

        public function set book_type(value:int):void {
            _book_type = value;
        }
        public function get book_type():int {
            return _book_type;
        }

        public function set book_type_name(value:String):void {
            _book_type_name = value;
        }
        public function get book_type_name():String {
            return _book_type_name;
        }

        public function set butt(value:int):void {
            _butt = value;
        }
        public function get butt():int {
            return _butt;
        }

        public function set correction(value:int):void {
            _correction = value;
        }
        public function get correction():int {
            return _correction;
        }

        public function set correction_name(value:String):void {
            _correction_name = value;
        }
        public function get correction_name():String {
            return _correction_name;
        }

        public function set cutting(value:int):void {
            _cutting = value;
        }
        public function get cutting():int {
            return _cutting;
        }

        public function set cutting_name(value:String):void {
            _cutting_name = value;
        }
        public function get cutting_name():String {
            return _cutting_name;
        }

        public function set destination(value:int):void {
            _destination = value;
        }
        public function get destination():int {
            return _destination;
        }

        public function set file_num(value:int):void {
            _file_num = value;
        }
        public function get file_num():int {
            return _file_num;
        }

        public function set files(value:ListCollectionView):void {
            _files = value;
        }
        public function get files():ListCollectionView {
            return _files;
        }

        public function set frame(value:int):void {
            _frame = value;
        }
        public function get frame():int {
            return _frame;
        }

        public function set frame_name(value:String):void {
            _frame_name = value;
        }
        public function get frame_name():String {
            return _frame_name;
        }

        public function set height(value:int):void {
            _height = value;
        }
        public function get height():int {
            return _height;
        }

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function set is_duplex(value:Boolean):void {
            _is_duplex = value;
        }
        public function get is_duplex():Boolean {
            return _is_duplex;
        }

        public function set is_finalizeprint(value:Boolean):void {
            _is_finalizeprint = value;
        }
        public function get is_finalizeprint():Boolean {
            return _is_finalizeprint;
        }

        public function set is_pdf(value:Boolean):void {
            _is_pdf = value;
        }
        public function get is_pdf():Boolean {
            return _is_pdf;
        }

        public function set is_reprint(value:Boolean):void {
            _is_reprint = value;
        }
        public function get is_reprint():Boolean {
            return _is_reprint;
        }

        public function set is_revers(value:Boolean):void {
            _is_revers = value;
        }
        public function get is_revers():Boolean {
            return _is_revers;
        }

        public function set lab_name(value:String):void {
            _lab_name = value;
        }
        public function get lab_name():String {
            return _lab_name;
        }

        public function set order_folder(value:String):void {
            _order_folder = value;
        }
        public function get order_folder():String {
            return _order_folder;
        }

        public function set order_id(value:String):void {
            _order_id = value;
        }
        public function get order_id():String {
            return _order_id;
        }

        public function set paper(value:int):void {
            _paper = value;
        }
        public function get paper():int {
            return _paper;
        }

        public function set paper_name(value:String):void {
            _paper_name = value;
        }
        public function get paper_name():String {
            return _paper_name;
        }

        public function set path(value:String):void {
            _path = value;
        }
        public function get path():String {
            return _path;
        }

        public function set prints(value:int):void {
            _prints = value;
        }
        public function get prints():int {
            return _prints;
        }

        public function set prints_done(value:int):void {
            _prints_done = value;
        }
        public function get prints_done():int {
            return _prints_done;
        }

        public function set prn_queue(value:int):void {
            _prn_queue = value;
        }
        public function get prn_queue():int {
            return _prn_queue;
        }

        public function set reprint_id(value:String):void {
            _reprint_id = value;
        }
        public function get reprint_id():String {
            return _reprint_id;
        }

        public function set sheet_num(value:int):void {
            _sheet_num = value;
        }
        public function get sheet_num():int {
            return _sheet_num;
        }

        public function set sheets_per_file(value:int):void {
            _sheets_per_file = value;
        }
        public function get sheets_per_file():int {
            return _sheets_per_file;
        }

        public function set source_id(value:int):void {
            _source_id = value;
        }
        public function get source_id():int {
            return _source_id;
        }

        public function set source_name(value:String):void {
            _source_name = value;
        }
        public function get source_name():String {
            return _source_name;
        }

        public function set state(value:int):void {
            _state = value;
        }
        public function get state():int {
            return _state;
        }

        public function set state_date(value:Date):void {
            _state_date = value;
        }
        public function get state_date():Date {
            return _state_date;
        }

        public function set state_name(value:String):void {
            _state_name = value;
        }
        public function get state_name():String {
            return _state_name;
        }

        public function set sub_id(value:String):void {
            _sub_id = value;
        }
        public function get sub_id():String {
            return _sub_id;
        }

        public function set width(value:int):void {
            _width = value;
        }
        public function get width():int {
            return _width;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _alias = input.readObject() as String;
            _book_num = input.readObject() as int;
            _book_part = input.readObject() as int;
            _book_part_name = input.readObject() as String;
            _book_type = input.readObject() as int;
            _book_type_name = input.readObject() as String;
            _butt = input.readObject() as int;
            _correction = input.readObject() as int;
            _correction_name = input.readObject() as String;
            _cutting = input.readObject() as int;
            _cutting_name = input.readObject() as String;
            _destination = input.readObject() as int;
            _file_num = input.readObject() as int;
            _files = input.readObject() as ListCollectionView;
            _frame = input.readObject() as int;
            _frame_name = input.readObject() as String;
            _height = input.readObject() as int;
            _id = input.readObject() as String;
            _is_duplex = input.readObject() as Boolean;
            _is_finalizeprint = input.readObject() as Boolean;
            _is_pdf = input.readObject() as Boolean;
            _is_reprint = input.readObject() as Boolean;
            _is_revers = input.readObject() as Boolean;
            _lab_name = input.readObject() as String;
            _order_folder = input.readObject() as String;
            _order_id = input.readObject() as String;
            _paper = input.readObject() as int;
            _paper_name = input.readObject() as String;
            _path = input.readObject() as String;
            _prints = input.readObject() as int;
            _prints_done = input.readObject() as int;
            _prn_queue = input.readObject() as int;
            _reprint_id = input.readObject() as String;
            _sheet_num = input.readObject() as int;
            _sheets_per_file = input.readObject() as int;
            _source_id = input.readObject() as int;
            _source_name = input.readObject() as String;
            _state = input.readObject() as int;
            _state_date = input.readObject() as Date;
            _state_name = input.readObject() as String;
            _sub_id = input.readObject() as String;
            _width = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_alias);
            output.writeObject(_book_num);
            output.writeObject(_book_part);
            output.writeObject(_book_part_name);
            output.writeObject(_book_type);
            output.writeObject(_book_type_name);
            output.writeObject(_butt);
            output.writeObject(_correction);
            output.writeObject(_correction_name);
            output.writeObject(_cutting);
            output.writeObject(_cutting_name);
            output.writeObject(_destination);
            output.writeObject(_file_num);
            output.writeObject(_files);
            output.writeObject(_frame);
            output.writeObject(_frame_name);
            output.writeObject(_height);
            output.writeObject(_id);
            output.writeObject(_is_duplex);
            output.writeObject(_is_finalizeprint);
            output.writeObject(_is_pdf);
            output.writeObject(_is_reprint);
            output.writeObject(_is_revers);
            output.writeObject(_lab_name);
            output.writeObject(_order_folder);
            output.writeObject(_order_id);
            output.writeObject(_paper);
            output.writeObject(_paper_name);
            output.writeObject(_path);
            output.writeObject(_prints);
            output.writeObject(_prints_done);
            output.writeObject(_prn_queue);
            output.writeObject(_reprint_id);
            output.writeObject(_sheet_num);
            output.writeObject(_sheets_per_file);
            output.writeObject(_source_id);
            output.writeObject(_source_name);
            output.writeObject(_state);
            output.writeObject(_state_date);
            output.writeObject(_state_name);
            output.writeObject(_sub_id);
            output.writeObject(_width);
        }
    }
}