/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrintFormParametr.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PrintFormParametrBase extends AbstractEntity {

        public function PrintFormParametrBase() {
            super();
        }

        private var _form:int;
        private var _form_field:int;
        private var _parametr:String;
        private var _simplex:Boolean;

        public function set form(value:int):void {
            _form = value;
        }
        public function get form():int {
            return _form;
        }

        public function set form_field(value:int):void {
            _form_field = value;
        }
        public function get form_field():int {
            return _form_field;
        }

        public function set parametr(value:String):void {
            _parametr = value;
        }
        public function get parametr():String {
            return _parametr;
        }

        public function set simplex(value:Boolean):void {
            _simplex = value;
        }
        public function get simplex():Boolean {
            return _simplex;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _form = input.readObject() as int;
            _form_field = input.readObject() as int;
            _parametr = input.readObject() as String;
            _simplex = input.readObject() as Boolean;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_form);
            output.writeObject(_form_field);
            output.writeObject(_parametr);
            output.writeObject(_simplex);
        }
    }
}