/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	import com.photodispatcher.util.GridUtil;
	
	import flash.globalization.DateTimeStyle;
	
	import mx.collections.ArrayList;
	
	import spark.components.gridClasses.GridColumn;
	import spark.formatters.DateTimeFormatter;

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.PrnQueue")]
    public class PrnQueue extends PrnQueueBase {

		public static function gridColumns():ArrayList{
			var result:Array= [];
			var col:GridColumn;
			
			col= new GridColumn('strategy_type_name'); col.headerText='Стратегия'; result.push(col);
			col= new GridColumn('label'); col.headerText='Наименование'; result.push(col);
			col= new GridColumn('sub_queue'); col.headerText='№'; col.width=50; result.push(col);
			//			col= new GridColumn('is_active'); col.headerText='Активна'; col.width=50; col.labelFunction=GridUtil.booleanToLabel; result.push(col);
			col= new GridColumn('is_active'); col.headerText='Активна'; col.labelFunction=GridUtil.booleanToLabel; col.width=50; result.push(col);
			col= new GridColumn('is_reprint'); col.headerText='Перепечатка'; col.labelFunction=GridUtil.booleanToLabel; col.width=50; result.push(col);
			col= new GridColumn('priority'); col.headerText='Приоритет'; col.width=50; result.push(col);
			var fmt:DateTimeFormatter=new DateTimeFormatter(); fmt.dateStyle=fmt.timeStyle=DateTimeStyle.SHORT;
			col= new GridColumn('created'); col.headerText='Создана'; col.formatter=fmt;  col.width=100; result.push(col);
			col= new GridColumn('started'); col.headerText='Старт'; col.formatter=fmt;  col.width=100; result.push(col);
			col= new GridColumn('complited'); col.headerText='Завершена'; col.formatter=fmt;  col.width=100; result.push(col);
			col= new GridColumn('lab_name'); col.headerText='Лаба'; result.push(col);
			
			return new ArrayList(result);
		}

        public function PrnQueue() {
            super();
        }
    }
}