/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrnQueue.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class PrnQueueBase extends AbstractEntity {

        public function PrnQueueBase() {
            super();
        }

        private var _complited:Date;
        private var _created:Date;
        private var _has_sub:Boolean;
        private var _id:int;
        private var _is_active:Boolean;
        private var _lab:int;
        private var _label:String;
        private var _started:Date;
        private var _strategy:int;
        private var _strategy_name:String;
        private var _strategy_type:int;
        private var _strategy_type_name:String;

        public function set complited(value:Date):void {
            _complited = value;
        }
        public function get complited():Date {
            return _complited;
        }

        public function set created(value:Date):void {
            _created = value;
        }
        public function get created():Date {
            return _created;
        }

        public function set has_sub(value:Boolean):void {
            _has_sub = value;
        }
        public function get has_sub():Boolean {
            return _has_sub;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set is_active(value:Boolean):void {
            _is_active = value;
        }
        public function get is_active():Boolean {
            return _is_active;
        }

        public function set lab(value:int):void {
            _lab = value;
        }
        public function get lab():int {
            return _lab;
        }

        public function set label(value:String):void {
            _label = value;
        }
        public function get label():String {
            return _label;
        }

        public function set started(value:Date):void {
            _started = value;
        }
        public function get started():Date {
            return _started;
        }

        public function set strategy(value:int):void {
            _strategy = value;
        }
        public function get strategy():int {
            return _strategy;
        }

        public function set strategy_name(value:String):void {
            _strategy_name = value;
        }
        public function get strategy_name():String {
            return _strategy_name;
        }

        public function set strategy_type(value:int):void {
            _strategy_type = value;
        }
        public function get strategy_type():int {
            return _strategy_type;
        }

        public function set strategy_type_name(value:String):void {
            _strategy_type_name = value;
        }
        public function get strategy_type_name():String {
            return _strategy_type_name;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _complited = input.readObject() as Date;
            _created = input.readObject() as Date;
            _has_sub = input.readObject() as Boolean;
            _id = input.readObject() as int;
            _is_active = input.readObject() as Boolean;
            _lab = input.readObject() as int;
            _label = input.readObject() as String;
            _started = input.readObject() as Date;
            _strategy = input.readObject() as int;
            _strategy_name = input.readObject() as String;
            _strategy_type = input.readObject() as int;
            _strategy_type_name = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_complited is IPropertyHolder) ? IPropertyHolder(_complited).object : _complited);
            output.writeObject((_created is IPropertyHolder) ? IPropertyHolder(_created).object : _created);
            output.writeObject((_has_sub is IPropertyHolder) ? IPropertyHolder(_has_sub).object : _has_sub);
            output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id);
            output.writeObject((_is_active is IPropertyHolder) ? IPropertyHolder(_is_active).object : _is_active);
            output.writeObject((_lab is IPropertyHolder) ? IPropertyHolder(_lab).object : _lab);
            output.writeObject((_label is IPropertyHolder) ? IPropertyHolder(_label).object : _label);
            output.writeObject((_started is IPropertyHolder) ? IPropertyHolder(_started).object : _started);
            output.writeObject((_strategy is IPropertyHolder) ? IPropertyHolder(_strategy).object : _strategy);
            output.writeObject((_strategy_name is IPropertyHolder) ? IPropertyHolder(_strategy_name).object : _strategy_name);
            output.writeObject((_strategy_type is IPropertyHolder) ? IPropertyHolder(_strategy_type).object : _strategy_type);
            output.writeObject((_strategy_type_name is IPropertyHolder) ? IPropertyHolder(_strategy_type_name).object : _strategy_type_name);
        }
    }
}