/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {
	import com.photodispatcher.util.GridUtil;
	import com.photodispatcher.view.itemRenderer.BooleanGridItemEditor;
	import com.photodispatcher.view.itemRenderer.CBoxGridItemEditor;
	import com.photodispatcher.view.itemRenderer.TimeGridEditor;
	
	import flash.globalization.DateTimeStyle;
	
	import mx.collections.ArrayList;
	import mx.core.ClassFactory;
	
	import spark.components.gridClasses.GridColumn;
	import spark.formatters.DateTimeFormatter;

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.PrnQueueTimetable")]
    public class PrnQueueTimetable extends PrnQueueTimetableBase {

		public static function gridColumns():ArrayList{
			var result:ArrayList= new ArrayList();
			var col:GridColumn;
			col= new GridColumn('is_active'); col.headerText='Активна ';  col.labelFunction=GridUtil.booleanToLabel; col.itemEditor=new ClassFactory(BooleanGridItemEditor); col.width=60; result.addItem(col);
			col= new GridColumn('lab_type'); col.headerText='Тип лабы'; col.labelFunction=GridUtil.idToLabel; col.itemEditor=new ClassFactory(CBoxGridItemEditor); result.addItem(col);
			col= new GridColumn('strategy_type'); col.headerText='Стратегия'; col.labelFunction=GridUtil.idToLabel; col.itemEditor=new ClassFactory(CBoxGridItemEditor); result.addItem(col);
			var fmt:DateTimeFormatter=new DateTimeFormatter(); fmt.dateTimePattern='HH:mm'; fmt.useUTC=false;
			col= new GridColumn('time_start'); col.headerText='Время запуска'; col.formatter=fmt; col.itemEditor=new ClassFactory(TimeGridEditor); col.width=100; result.addItem(col);
			fmt=new DateTimeFormatter(); fmt.dateStyle=fmt.timeStyle=DateTimeStyle.SHORT; 
			col= new GridColumn('last_start'); col.headerText='Последний запуск'; col.formatter=fmt; col.editable=false;  result.addItem(col);
			
			return result;
		}
		
        public function PrnQueueTimetable() {
            super();
        }
		
		public function isTimeToStart():Boolean{
			if(!time_start || !is_active || (time_start.hours==0 && time_start.minutes==0)) return false;
			if(lab_type==0 || strategy_type==0) return false; 
			var now:Date = new Date;
			var currDay:Date = new Date(now.fullYear,now.month,now.date);
			var start:Date= new Date(time_start.time);
			start.date=1; start.fullYear=now.fullYear; start.month=now.month; start.date=now.date;
			return (now.time>=start.time && (!last_start || last_start.time<currDay.time));
		}

    }
}