/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrnQueueItems.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PrnQueueItemsBase extends AbstractEntity {

        public function PrnQueueItemsBase() {
            super();
        }

        private var _print_group:String;
        private var _prn_queue:int;
        private var _seq:int;
        private var _sub_queue:int;

        public function set print_group(value:String):void {
            _print_group = value;
        }
        public function get print_group():String {
            return _print_group;
        }

        public function set prn_queue(value:int):void {
            _prn_queue = value;
        }
        public function get prn_queue():int {
            return _prn_queue;
        }

        public function set seq(value:int):void {
            _seq = value;
        }
        public function get seq():int {
            return _seq;
        }

        public function set sub_queue(value:int):void {
            _sub_queue = value;
        }
        public function get sub_queue():int {
            return _sub_queue;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _print_group = input.readObject() as String;
            _prn_queue = input.readObject() as int;
            _seq = input.readObject() as int;
            _sub_queue = input.readObject() as int;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_print_group);
            output.writeObject(_prn_queue);
            output.writeObject(_seq);
            output.writeObject(_sub_queue);
        }
    }
}