/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrnQueueTimetable.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PrnQueueTimetableBase extends AbstractEntity {

        public function PrnQueueTimetableBase() {
            super();
        }

        private var _booksonly:Boolean;
        private var _id:int;
        private var _is_active:Boolean;
        private var _lab_type:int;
        private var _lab_type_name:String;
        private var _last_start:Date;
        private var _last_start_c:Date;
        private var _strategy_type:int;
        private var _strategy_type_name:String;
        private var _time_start:Date;

        public function set booksonly(value:Boolean):void {
            _booksonly = value;
        }
        public function get booksonly():Boolean {
            return _booksonly;
        }

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set is_active(value:Boolean):void {
            _is_active = value;
        }
        public function get is_active():Boolean {
            return _is_active;
        }

        public function set lab_type(value:int):void {
            _lab_type = value;
        }
        public function get lab_type():int {
            return _lab_type;
        }

        public function set lab_type_name(value:String):void {
            _lab_type_name = value;
        }
        public function get lab_type_name():String {
            return _lab_type_name;
        }

        public function set last_start(value:Date):void {
            _last_start = value;
        }
        public function get last_start():Date {
            return _last_start;
        }

        public function set last_start_c(value:Date):void {
            _last_start_c = value;
        }
        public function get last_start_c():Date {
            return _last_start_c;
        }

        public function set strategy_type(value:int):void {
            _strategy_type = value;
        }
        public function get strategy_type():int {
            return _strategy_type;
        }

        public function set strategy_type_name(value:String):void {
            _strategy_type_name = value;
        }
        public function get strategy_type_name():String {
            return _strategy_type_name;
        }

        public function set time_start(value:Date):void {
            _time_start = value;
        }
        public function get time_start():Date {
            return _time_start;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _booksonly = input.readObject() as Boolean;
            _id = input.readObject() as int;
            _is_active = input.readObject() as Boolean;
            _lab_type = input.readObject() as int;
            _lab_type_name = input.readObject() as String;
            _last_start = input.readObject() as Date;
            _last_start_c = input.readObject() as Date;
            _strategy_type = input.readObject() as int;
            _strategy_type_name = input.readObject() as String;
            _time_start = input.readObject() as Date;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_booksonly);
            output.writeObject(_id);
            output.writeObject(_is_active);
            output.writeObject(_lab_type);
            output.writeObject(_lab_type_name);
            output.writeObject(_last_start);
            output.writeObject(_last_start_c);
            output.writeObject(_strategy_type);
            output.writeObject(_strategy_type_name);
            output.writeObject(_time_start);
        }
    }
}