/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (RackOrders.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class RackOrdersBase extends AbstractEntity {

        public function RackOrdersBase() {
            super();
        }

        private var _order_id:String;
        private var _rack_name:String;
        private var _space:int;
        private var _space_name:String;

        public function set order_id(value:String):void {
            _order_id = value;
        }
        public function get order_id():String {
            return _order_id;
        }

        public function set rack_name(value:String):void {
            _rack_name = value;
        }
        public function get rack_name():String {
            return _rack_name;
        }

        public function set space(value:int):void {
            _space = value;
        }
        public function get space():int {
            return _space;
        }

        public function set space_name(value:String):void {
            _space_name = value;
        }
        public function get space_name():String {
            return _space_name;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _order_id = input.readObject() as String;
            _rack_name = input.readObject() as String;
            _space = input.readObject() as int;
            _space_name = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_order_id is IPropertyHolder) ? IPropertyHolder(_order_id).object : _order_id);
            output.writeObject((_rack_name is IPropertyHolder) ? IPropertyHolder(_rack_name).object : _rack_name);
            output.writeObject((_space is IPropertyHolder) ? IPropertyHolder(_space).object : _space);
            output.writeObject((_space_name is IPropertyHolder) ? IPropertyHolder(_space_name).object : _space_name);
        }
    }
}