/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SelectResult.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class SelectResultBase extends SqlResult {

        private var _data:ListCollectionView;

        public function set data(value:ListCollectionView):void {
            _data = value;
        }
        public function get data():ListCollectionView {
            return _data;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _data = input.readObject() as ListCollectionView;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_data is IPropertyHolder) ? IPropertyHolder(_data).object : _data);
        }
    }
}