/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.photodispatcher.model.mysql.entities {

    [Bindable]
    [RemoteClass(alias="com.photodispatcher.model.mysql.entities.SourceSvc")]
    public class SourceSvc extends SourceSvcBase {
		public static const WEB_SERVICE:int=1;
		public static const FTP_SERVICE:int=4;
		public static const FBOOK_SERVICE:int=5;
		public static const HOT_FOLDER:int=10;

    }
}