/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (StaffActivity.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class StaffActivityBase extends AbstractEntity {

        public function StaffActivityBase() {
            super();
        }

        private var _id:int;
        private var _log_date:Date;
        private var _order_id:String;
        private var _pg_id:String;
        private var _remark:String;
        private var _sa_group:int;
        private var _sa_group_name:String;
        private var _sa_type:int;
        private var _sa_type_name:String;
        private var _staff:int;
        private var _staff_name:String;

        public function set id(value:int):void {
            _id = value;
        }
        public function get id():int {
            return _id;
        }

        public function set log_date(value:Date):void {
            _log_date = value;
        }
        public function get log_date():Date {
            return _log_date;
        }

        public function set order_id(value:String):void {
            _order_id = value;
        }
        public function get order_id():String {
            return _order_id;
        }

        public function set pg_id(value:String):void {
            _pg_id = value;
        }
        public function get pg_id():String {
            return _pg_id;
        }

        public function set remark(value:String):void {
            _remark = value;
        }
        public function get remark():String {
            return _remark;
        }

        public function set sa_group(value:int):void {
            _sa_group = value;
        }
        public function get sa_group():int {
            return _sa_group;
        }

        public function set sa_group_name(value:String):void {
            _sa_group_name = value;
        }
        public function get sa_group_name():String {
            return _sa_group_name;
        }

        public function set sa_type(value:int):void {
            _sa_type = value;
        }
        public function get sa_type():int {
            return _sa_type;
        }

        public function set sa_type_name(value:String):void {
            _sa_type_name = value;
        }
        public function get sa_type_name():String {
            return _sa_type_name;
        }

        public function set staff(value:int):void {
            _staff = value;
        }
        public function get staff():int {
            return _staff;
        }

        public function set staff_name(value:String):void {
            _staff_name = value;
        }
        public function get staff_name():String {
            return _staff_name;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _id = input.readObject() as int;
            _log_date = input.readObject() as Date;
            _order_id = input.readObject() as String;
            _pg_id = input.readObject() as String;
            _remark = input.readObject() as String;
            _sa_group = input.readObject() as int;
            _sa_group_name = input.readObject() as String;
            _sa_type = input.readObject() as int;
            _sa_type_name = input.readObject() as String;
            _staff = input.readObject() as int;
            _staff_name = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_id);
            output.writeObject(_log_date);
            output.writeObject(_order_id);
            output.writeObject(_pg_id);
            output.writeObject(_remark);
            output.writeObject(_sa_group);
            output.writeObject(_sa_group_name);
            output.writeObject(_sa_type);
            output.writeObject(_sa_type_name);
            output.writeObject(_staff);
            output.writeObject(_staff_name);
        }
    }
}