/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TechTimeline.as).
 */

package com.photodispatcher.model.mysql.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class TechTimelineBase extends AbstractEntity {

        public function TechTimelineBase() {
            super();
        }

        private var _book_part:int;
        private var _book_part_name:String;
        private var _oper_time:int;
        private var _pass_time:int;
        private var _tech_process:int;
        private var _tech_type:int;
        private var _tech_type_name:String;

        public function set book_part(value:int):void {
            _book_part = value;
        }
        public function get book_part():int {
            return _book_part;
        }

        public function set book_part_name(value:String):void {
            _book_part_name = value;
        }
        public function get book_part_name():String {
            return _book_part_name;
        }

        public function set oper_time(value:int):void {
            _oper_time = value;
        }
        public function get oper_time():int {
            return _oper_time;
        }

        public function set pass_time(value:int):void {
            _pass_time = value;
        }
        public function get pass_time():int {
            return _pass_time;
        }

        public function set tech_process(value:int):void {
            _tech_process = value;
        }
        public function get tech_process():int {
            return _tech_process;
        }

        public function set tech_type(value:int):void {
            _tech_type = value;
        }
        public function get tech_type():int {
            return _tech_type;
        }

        public function set tech_type_name(value:String):void {
            _tech_type_name = value;
        }
        public function get tech_type_name():String {
            return _tech_type_name;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _book_part = input.readObject() as int;
            _book_part_name = input.readObject() as String;
            _oper_time = input.readObject() as int;
            _pass_time = input.readObject() as int;
            _tech_process = input.readObject() as int;
            _tech_type = input.readObject() as int;
            _tech_type_name = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_book_part);
            output.writeObject(_book_part_name);
            output.writeObject(_oper_time);
            output.writeObject(_pass_time);
            output.writeObject(_tech_process);
            output.writeObject(_tech_type);
            output.writeObject(_tech_type_name);
        }
    }
}